set_property PACKAGE_PIN R8 [get_ports DIPSW0]
set_property IOSTANDARD SSTL15 [get_ports DIPSW0]
set_property PACKAGE_PIN P8 [get_ports DIPSW1]
set_property IOSTANDARD SSTL15 [get_ports DIPSW1]
set_property IOSTANDARD SSTL15 [get_ports DIPSW2]
set_property IOSTANDARD SSTL15 [get_ports DIPSW3]
set_property PACKAGE_PIN R7 [get_ports DIPSW2]
set_property PACKAGE_PIN R6 [get_ports DIPSW3]
set_property PACKAGE_PIN M26 [get_ports LED0]
set_property PACKAGE_PIN T24 [get_ports LED1]
set_property PACKAGE_PIN T25 [get_ports LED2]
set_property PACKAGE_PIN R26 [get_ports LED3]
set_property IOSTANDARD LVCMOS33 [get_ports LED0]
set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED3]
set_property PACKAGE_PIN P6 [get_ports PushButtonSW3]
set_property PACKAGE_PIN U5 [get_ports PushButtonSW4]
set_property PACKAGE_PIN U6 [get_ports PushButtonSW6]
set_property PACKAGE_PIN R5 [get_ports PushButtonSW7]
set_property IOSTANDARD SSTL15 [get_ports PushButtonSW3]
set_property IOSTANDARD SSTL15 [get_ports PushButtonSW4]
set_property IOSTANDARD SSTL15 [get_ports PushButtonSW6]
set_property IOSTANDARD SSTL15 [get_ports PushButtonSW7]
#set_property PACKAGE_PIN R3 [get_ports SysClk]
#set_property IOSTANDARD LVCMOS25 [get_ports SysClk]


set_property PACKAGE_PIN R3 [get_ports SysClk_P]
set_property IOSTANDARD LVDS_25 [get_ports SysClk_P]
set_property PACKAGE_PIN F25 [get_ports LED_RCO]
set_property IOSTANDARD LVCMOS33 [get_ports LED_RCO]


set_property PACKAGE_PIN H26 [get_ports LED_SWAP]
set_property IOSTANDARD LVCMOS33 [get_ports LED_SWAP]

set_property PACKAGE_PIN T5 [get_ports PushButtonSW5]
set_property IOSTANDARD SSTL15 [get_ports PushButtonSW5]

set_property PACKAGE_PIN M26 [get_ports {LEDs[0]}]
set_property PACKAGE_PIN T24 [get_ports {LEDs[1]}]
set_property PACKAGE_PIN T25 [get_ports {LEDs[2]}]
set_property PACKAGE_PIN R26 [get_ports {LEDs[3]}]
set_property PACKAGE_PIN F25 [get_ports {LEDs[4]}]
set_property PACKAGE_PIN G25 [get_ports {LEDs[5]}]
set_property PACKAGE_PIN G26 [get_ports {LEDs[6]}]
set_property PACKAGE_PIN H26 [get_ports {LEDs[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LEDs[3]}]
