# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/stargrif/VhdlLabs/Lab4/Lab4.cache/wt [current_project]
set_property parent.project_path /home/stargrif/VhdlLabs/Lab4/Lab4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:ac701:part0:1.2 [current_project]
read_vhdl -library xil_defaultlib {
  /home/stargrif/VhdlLabs/Lab4/Lab4.srcs/sources_1/imports/new/D_trigger.vhd
  /home/stargrif/VhdlLabs/Lab4/Lab4.srcs/sources_1/imports/new/Divider.vhd
  /home/stargrif/VhdlLabs/Lab4/Lab4.srcs/sources_1/imports/new/SyncCountUD.vhd
  /home/stargrif/VhdlLabs/Lab4/Lab4.srcs/sources_1/new/ControlDev.vhd
}
read_xdc /home/stargrif/VhdlLabs/Lab4/Lab4.srcs/constrs_1/imports/new/CommonConstr.xdc
set_property used_in_implementation false [get_files /home/stargrif/VhdlLabs/Lab4/Lab4.srcs/constrs_1/imports/new/CommonConstr.xdc]

synth_design -top ControlDev -part xc7a200tfbg676-2
write_checkpoint -noxdef ControlDev.dcp
catch { report_utilization -file ControlDev_utilization_synth.rpt -pb ControlDev_utilization_synth.pb }
